.PHONY: proto build

proto:
	protoc --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
		proto/auth.proto proto/notifications.proto

build:
	go build -o bin/backend .

run:
	go run .

