package constants

const (
	// Order Status Codes - ORDER PLACED
	ORDER_STATUS_PENDING        = "pending"
	ORDER_STATUS_CANCELED       = "canceled"
	ORDER_STATUS_REJECTED       = "rejected"
	ORDER_STATUS_REJECTED_BY_USER = "rejected_by_user"

	// Order Status Codes - SELLER DISPATCH
	ORDER_STATUS_SELLER_NOTIFIED         = "seller_notified"
	ORDER_STATUS_SELLER_PROCESSING       = "seller_processing"
	ORDER_STATUS_SELLER_WAITING_DISPATCH = "seller_waiting_dispatch"
	ORDER_STATUS_SELLER_DISPATCHED       = "seller_dispatched"

	// Order Status Codes - SHIPPING AGENT
	ORDER_STATUS_AGENT_PICKED          = "agent_picked"
	ORDER_STATUS_AGENT_TRANSPORTING    = "agent_transporting"
	ORDER_STATUS_AGENT_OUT_FOR_DELIVERY = "agent_out_for_delivery"
	ORDER_STATUS_ORDER_DELIVERED       = "order_delivered"

	// Order Status Codes - USERS
	ORDER_STATUS_USER_CANCELLED_ON_ARRIVAL = "user_cancelled_on_arrival"
	ORDER_STATUS_USER_CANCELLED           = "user_cancelled"
	ORDER_STATUS_USER_RETURNED             = "user_returned"

	// Order Status Codes - PAYMENT DISPUTE / REFUND FLOW
	ORDER_STATUS_USER_RETURNING        = "user_returning"
	ORDER_STATUS_USER_RETURN_RECEIVED  = "user_return_received"
	ORDER_STATUS_USER_REFUND_INITIATED = "user_refund_initiated"
	ORDER_STATUS_USER_REFUND_FAILED    = "user_refund_failed"
	ORDER_STATUS_USER_REFUND_PROCESSED = "user_refund_processed"
)

var OrderStatusCodes = struct {
	PENDING                  string
	CANCELED                 string
	REJECTED                 string
	REJECTED_BY_USER         string
	SELLER_NOTIFIED          string
	SELLER_PROCESSING        string
	SELLER_WAITING_DISPATCH  string
	SELLER_DISPATCHED        string
	AGENT_PICKED             string
	AGENT_TRANSPORTING       string
	AGENT_OUT_FOR_DELIVERY   string
	ORDER_DELIVERED          string
	USER_CANCELLED_ON_ARRIVAL string
	USER_CANCELLED           string
	USER_RETURNED            string
	USER_RETURNING           string
	USER_RETURN_RECEIVED     string
	USER_REFUND_INITIATED    string
	USER_REFUND_FAILED       string
	USER_REFUND_PROCESSED    string
}{
	PENDING:                  ORDER_STATUS_PENDING,
	CANCELED:                 ORDER_STATUS_CANCELED,
	REJECTED:                 ORDER_STATUS_REJECTED,
	REJECTED_BY_USER:         ORDER_STATUS_REJECTED_BY_USER,
	SELLER_NOTIFIED:          ORDER_STATUS_SELLER_NOTIFIED,
	SELLER_PROCESSING:        ORDER_STATUS_SELLER_PROCESSING,
	SELLER_WAITING_DISPATCH:  ORDER_STATUS_SELLER_WAITING_DISPATCH,
	SELLER_DISPATCHED:        ORDER_STATUS_SELLER_DISPATCHED,
	AGENT_PICKED:             ORDER_STATUS_AGENT_PICKED,
	AGENT_TRANSPORTING:       ORDER_STATUS_AGENT_TRANSPORTING,
	AGENT_OUT_FOR_DELIVERY:   ORDER_STATUS_AGENT_OUT_FOR_DELIVERY,
	ORDER_DELIVERED:          ORDER_STATUS_ORDER_DELIVERED,
	USER_CANCELLED_ON_ARRIVAL: ORDER_STATUS_USER_CANCELLED_ON_ARRIVAL,
	USER_CANCELLED:           ORDER_STATUS_USER_CANCELLED,
	USER_RETURNED:            ORDER_STATUS_USER_RETURNED,
	USER_RETURNING:           ORDER_STATUS_USER_RETURNING,
	USER_RETURN_RECEIVED:     ORDER_STATUS_USER_RETURN_RECEIVED,
	USER_REFUND_INITIATED:    ORDER_STATUS_USER_REFUND_INITIATED,
	USER_REFUND_FAILED:       ORDER_STATUS_USER_REFUND_FAILED,
	USER_REFUND_PROCESSED:    ORDER_STATUS_USER_REFUND_PROCESSED,
}

const (
	// Event Names
	EVENT_ORDER_CREATED  = "order.created"
	EVENT_ORDER_UPDATED  = "order.updated"
	EVENT_PRODUCT_CREATED = "product.created"
	EVENT_PRODUCT_DELETED = "product.deleted"
)

var EventNames = struct {
	ORDER_CREATED  string
	ORDER_UPDATED  string
	PRODUCT_CREATED string
	PRODUCT_DELETED string
}{
	ORDER_CREATED:  EVENT_ORDER_CREATED,
	ORDER_UPDATED:  EVENT_ORDER_UPDATED,
	PRODUCT_CREATED: EVENT_PRODUCT_CREATED,
	PRODUCT_DELETED: EVENT_PRODUCT_DELETED,
}

const (
	// Plugin Targets
	PLUGIN_TARGET_DISCORD_ORDERS   = "discord-orders"
	PLUGIN_TARGET_TELEGRAM_ORDERS   = "telegram-orders"
	PLUGIN_TARGET_DISCORD_PRODUCTS = "discord-products"
)

var PluginTargets = struct {
	DISCORD_ORDERS   string
	TELEGRAM_ORDERS  string
	DISCORD_PRODUCTS string
}{
	DISCORD_ORDERS:   PLUGIN_TARGET_DISCORD_ORDERS,
	TELEGRAM_ORDERS:  PLUGIN_TARGET_TELEGRAM_ORDERS,
	DISCORD_PRODUCTS: PLUGIN_TARGET_DISCORD_PRODUCTS,
}

